# vot makefile
#
# Author   : Mi,Liang (Arizona State University)
# Email    : icemiliang@gmail.com
# Date     : Oct 16th 2018

all:
	$(MAKE) -C vot
	$(MAKE) -C votx

clean:
	$(MAKE) -C vot clean
	$(MAKE) -C votx clean
